<a href="https://colab.research.google.com/github/sakshi0109/MachineLearning/blob/master/beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.12161008,  1.0014447 ,  0.40947074, -0.1092089 , -0.47574583,
        -0.27927044,  0.5249678 , -1.1020098 , -0.14088148,  0.10191229]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07776689, 0.23907337, 0.13226356, 0.07873729, 0.05457522,
        0.0664238 , 0.14845674, 0.02917511, 0.07628256, 0.09724543]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.7117

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2950 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1437 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1088 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0887 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0767 - accuracy: 0.9758


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0705 - accuracy: 0.9775


[0.07048316299915314, 0.9775000214576721]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0206545e-07, 5.2751869e-08, 4.1447415e-06, 5.0171919e-05,
        5.9841971e-12, 9.5877908e-07, 9.8170864e-13, 9.9994361e-01,
        2.7154167e-07, 7.0437721e-07],
       [3.2806644e-09, 1.4067345e-05, 9.9997449e-01, 1.1360055e-05,
        8.4742146e-17, 1.2367622e-08, 9.6071840e-12, 3.4829144e-14,
        1.4873898e-07, 9.5395405e-14],
       [2.3664235e-07, 9.9917907e-01, 2.2658318e-05, 3.8522348e-06,
        1.3648609e-05, 2.2256647e-07, 6.0868638e-06, 6.6330406e-04,
        1.1018991e-04, 6.5257785e-07],
       [9.9916232e-01, 7.7108234e-07, 5.6349207e-04, 7.5227163e-06,
        5.3105627e-08, 3.8497630e-05, 8.2369945e-05, 8.2311133e-05,
        3.7803423e-07, 6.2443381e-05],
       [1.4399872e-05, 6.3597531e-07, 3.0194467e-05, 2.7894893e-07,
        9.9607509e-01, 4.6414252e-07, 9.6570666e-06, 2.4085931e-04,
        9.9940671e-06, 3.6183966e-03]], dtype=float32)>